spring:
  profiles:
    active: dev
  datasource:
    driver-class-name:
    # driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:mariadb://127.0.0.1:3306/app_2022_10_01?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: jinsu291
    password: tn8817